### ISSUE TITLE
The "Cancel" button did not cancel the bake action

### ISSUE THREAD

**Issue by CrossVadar** [guycalledfrank/bakery-issues#146] opened 2023-03-12 02:41 UTC
I have tried to cancel the bake after clicking Rendering but it still kept on going without saving anything and stop the baking process.

**Comment by guycalledfrank** [comment] 2023-03-12 08:33
Duplicate of https://github.com/guycalledfrank/bakery-issues/issues/147

**Closed as completed by guycalledfrank** 2023-03-12 08:33 UTC
