### ISSUE TITLE
how do you add volume lighting to a hlsl in urp?

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#56] opened 2020-12-15 00:16 UTC
as much as i like graph shader, most powerful shaders out there are hlsl.
so how do I add volume lighting to that, is there a block I can copy paste and do my own lighting mixing?

**Comment by guycalledfrank** [comment] 2020-12-19 10:18
Duplicate of https://github.com/guycalledfrank/bakery-issues/issues/62

**Closed by guycalledfrank** 2020-12-19 10:18 UTC

**Comment by guycalledfrank** [comment] 2020-12-19 10:26
All useful function are inside BakeryDecodeLightmap.hlsl. If you have a basic HLSL shader that outputs some color/texture, you can #include "BakeryDecodeLightmap.hlsl" and use my function:

void BakeryVolume_float(float3 posWorld, float3 normalWorld, out float3 sh)

- posWorld is the world position, it should be calculated in VS as mul(unity_ObjectToWorld, IN.Position).xyz andd passed down to PS.
- normalWorld is world normal. Vertex normal can be computed similar to position: normalize(mul((float3x3)unity_ObjectToWorld, IN.Normal)), normal-mapped normals are a bit beyond the scope of this issue (but you can check my PerPixelWorldNormal.shadersubgraph for reference).
- sh is the output color. Just multiply it by albedo and return.

There is also a more advanced function with specular support:

void BakeryVolumeSpec_float(float3 posWorld, float3 normalWorld, float3 viewDir, float smoothness, float3 albedo, float metalness, out float3 diffuseSH, out float3 specularSH)

Additional parameters are:
- viewDir: world-space view vector. Can be computed as normalize(_WorldSpaceCameraPos - posWorld) (maybe with different sign).
- smoothness, albedo, metalness are self-explanatory.
- diffuseSH and specularSH are the outputs. Specular is pre-multiplied by fresnel, you can just add it to the final value.

**Comment by laurentopia** [comment] 2020-12-20 00:56
Thanks you! 
And does BakeryVolumeSpec_float turn into BakeryVolume_float if specularSH isn't used?
(Could you add that in the doc so it doesn't get lost in github?)
