### ISSUE TITLE
Undesirable bright spots around edges

### ISSUE THREAD

**Issue by tkggwatson** [guycalledfrank/bakery-issues#14] opened 2020-05-10 11:19 UTC
Hi there,

I'm trying to use Bakery to get a nice indirect ambient bake to blend with my realtime directional sunlight.

Artistically I want to achieve a lot of colour bleed between surfaces, so e.g. an orange wall should spill a lot of orange on to the floor below it. For this I'm using no direct bakery lights, and just a single skybox light with a flat light grey-blue colour, no texture, intensity set to 3 and indirect intensity set to 2 (side question - I can't actually tell what the difference is between these two, they both just seem to make the lightmap brighter?).

This produces the colour bleed effect I am after, but there are very undesirable white spots around close edges. Take a look at the attached screenshot around where the pavement joins the road surface.

How can I achieve the quantity of colour bleed I am after (or more!) without getting these bright dots? I notice even with the skybox intensity settings set to 1 I still see the bright spots, they just aren't as prominent.

I am using Unity 2019.3.13f1, Bakery 1.71, Universal Render Pipeline 7.3.1, with a GeForce RTX 2070. I don't think it should affect anything but I am also using EnviroSky for my skybox.

Thanks
Graham

![Fireflies](https://user-images.githubusercontent.com/29194421/81497708-042e4380-92b8-11ea-8d74-c1784aba9a33.png)

![Skylight](https://user-images.githubusercontent.com/29194421/81497732-38a1ff80-92b8-11ea-8140-f07dedeec449.png)

![BakerySettings](https://user-images.githubusercontent.com/29194421/81497734-3c358680-92b8-11ea-997c-8504cfc73035.png)

**Comment by guycalledfrank** [comment] 2020-05-10 11:42
>I can't actually tell what the difference is between these two, they both just seem to make the lightmap brighter?).

Indirect intensity only affects bounced lighting. Intensity affects direct lighting coming from skylight.

Regarding spots: yup, that doesn't look right and shouldn't happen. Can you check if it happens without denosing?

**Comment by tkggwatson** [comment] 2020-05-10 13:41
Hi @guycalledfrank , nice to meet you. Thanks for the quick response and great work on this lightmapper!

Turning off denoise does look like it improves it, though it is a little hard to tell as the result is extremely speckled. I've attached 2 images to show the difference.

Thanks
Graham

![WithDenoise](https://user-images.githubusercontent.com/29194421/81500785-537e6f00-92cc-11ea-9bab-df3bf27824cb.png)

![NoDenoise](https://user-images.githubusercontent.com/29194421/81500788-58432300-92cc-11ea-9e6c-f4ff6ff859a7.png)

**Comment by guycalledfrank** [comment] 2020-05-10 13:54
Thanks Graham!
This is... quite speckled for a single gray sky light. I'm assuming you have lots of emissive objects here? Can you check if it's them causing the effect? Very small/bright emissives can be noisy and are good candidates for Light Mesh component usage. Can you also check if using Legacy Denoiser (https://geom.io/bakery/wiki/index.php?title=Manual#Legacy_denoiser) works better than the default one?

**Comment by tkggwatson** [comment] 2020-05-10 14:35
The Legacy Denoiser looks a little better, though artefacts are still visible.

![LegacyDenoiser](https://user-images.githubusercontent.com/29194421/81501949-e8846680-92d2-11ea-8c9d-559c48788efd.png)

There are a couple of emissive lights over on the building at the back of the picture - a bright sign above the window. Above us in this image there are emissive neon lights running along the underside of a pathway, and the windows in the building have custom metapasses with high emissive so I get the nice sprawling white in front of them (visible at the top left of the images).

However these are there to give the light bleed effect I'm after - notice how the ground here is quite pink, that's from the neon lights above it on the underside of the pathway.

However - on the very first image I posted, there were no emissive surfaces near that that I know of.

**Comment by guycalledfrank** [comment] 2020-05-10 14:42
There is a hard-to-fix (because I can't control meta pass shaders) issue with emissives making them sometimes bleed over other objects when packed in a lightmap. I recommend you to try Light Meshes (https://geom.io/bakery/wiki/index.php?title=Manual#Bakery_Light_Mesh) for most of your emissive lights apart from either very small/dim or really large. Light meshes don't need to be packed to light maps and can't leak over unrelated charts; they also give higher quality distant lighting (less noise). Hopefully it's not hard to convert them in your case.

**Comment by tkggwatson** [comment] 2020-05-10 15:56
I've disabled all emissive in my scene, and I'm still seeing the artifacts. See screenshots below:

![NoEmissive](https://user-images.githubusercontent.com/29194421/81504004-db6d7480-92de-11ea-92fa-d402287d555f.png)

Below is the 'Emission' view from Unity's Progressive CPU, showing that the metapasses are outputting black for all my shaders. This seems to be coming purely from albedo?

![EmissionMeta](https://user-images.githubusercontent.com/29194421/81504059-3606d080-92df-11ea-9a10-e7cec518f9e6.png)

**Comment by tkggwatson** [comment] 2020-05-10 16:05
Also to double check that I've got things disabled properly, here is a screenshot of the generated lightmap with the skylight disabled, so I think this rules out emissive surfaces as the problem?

![NoSkyLight](https://user-images.githubusercontent.com/29194421/81504311-61d68600-92e0-11ea-8a60-f293d4e0ab33.png)

**Comment by tkggwatson** [comment] 2020-05-10 16:15
One more test - this is with the skylight re-enabled and the intensity and indirect intensity reset to 1. There are still artifacts here, and this now is with no special or extreme settings.

![SkylightIntensity1](https://user-images.githubusercontent.com/29194421/81504551-e675d400-92e1-11ea-9235-d507047e6ced.png)

**Comment by guycalledfrank** [comment] 2020-05-10 16:24
OK, this is confusing. Can you detach a small part of this scene and send it to me as unitypackage? I can probably ask you another dozen of questions, but it'll be quicker to just go over the scene and test things myself.

**Comment by tkggwatson** [comment] 2020-05-10 16:52
Certainly. Thank you for your help. Is there a private address I can send the package to please as I don't want to share our shaders etc. on here.

**Comment by guycalledfrank** [comment] 2020-05-10 18:04
somemail256 at gmail.com

**Comment by tkggwatson** [comment] 2020-05-10 22:31
I've sent you an email with the unitypackage attached. Thanks!

**Comment by guycalledfrank** [comment] 2020-05-13 14:25
... so the problem was caused by 
* Denoiser acting weirdly on RTX 2070
* Texture compression

Mostly fixed by:
- Using newly added OpenImageDenoise option
- Setting backface GI to 1 to remove dark shadows inside objects, thus making the texture smoother

**Closed by guycalledfrank** 2020-05-13 14:25 UTC
