### ISSUE TITLE
Light Color dosen't match

### ISSUE THREAD

**Issue by hu78h** [guycalledfrank/bakery-issues#114] opened 2021-07-19 07:33 UTC
Hello, after updating the latest patch, I noticed the Light color always doesn't match.
![image](https://user-images.githubusercontent.com/4949353/126120379-47844c82-1188-41d1-b205-3fd19efb3ad6.png)
And I think it is due to _commit d98bcf0c775b87513b2519449a35ff9ab0d61641_ which "take light color temperature into account for direct/point/area lights"

**Comment by pedropla** [comment] 2021-07-23 03:00
I have experienced this as well.

**Comment by guycalledfrank** [comment] 2021-07-26 14:23
Ouch. OK, seems to be fixed now: https://github.com/guycalledfrank/bakery-csharp/commit/4feacfa0e83f90f883e2d597f30a74628049164b

**Comment by pedropla** [comment] 2021-08-04 08:40
I'm still experiencing this issue with the latest version updated through the Bakery -> Utility -> Check for patches. Is the bug fix not in that branch or could it be something else?

Here's an example:
![image](https://user-images.githubusercontent.com/13673481/128150350-1dcf4699-4e41-4b54-a4e8-ecfc7ff90168.png)

**Comment by guycalledfrank** [comment] 2021-08-04 11:00
Did you restart the editor after the "check for patches" and clicked "yes" on the window that appeared after the restart?

**Comment by pedropla** [comment] 2021-08-04 11:14
Yes, and several updates since then.

**Comment by guycalledfrank** [comment] 2021-08-04 12:12
What is your
- Unity version
- Rendering pipeline
- Color space
- ?

**Comment by pedropla** [comment] 2021-08-04 12:47
2019.4.28f, built-in, linear color space

**Comment by guycalledfrank** [comment] 2021-08-04 12:57
I didn't have 2019.4.28, but I tried to reproduce it on 2019.4.3, and I couldn't. Both match buttons seem to work.
Are these options disabled on your light?

![image](https://user-images.githubusercontent.com/7008423/128184577-14ae8ddb-4c70-45c9-ae9e-f637510f085a.png)

**Comment by pedropla** [comment] 2021-08-05 01:32
Yes the options are disabled. Should I try enabling them?

And just in case, these are the hashes of the versions I have from bakery-compiled-cver.txt (c4619eaa47417fe26ecc2f0d8182c893d528c3de) and bakery-csharp-cver.txt (3d0ba1f839bfbac4e2b600ea74f97b9489d755d7). If those aren't versions that include patches then perhaps there's a problem installing updates through the git system.

![image](https://user-images.githubusercontent.com/13673481/128276755-9ec952dd-6c90-4f1b-871a-bd1a41c63efa.png)

**Comment by guycalledfrank** [comment] 2021-08-09 11:01
Your latest hash is correct, this is the version. Option should be off, as pictured. Can you send me this (or any where it's reproducible) project to test it? Maybe it's related to some project settings, I'm not sure.

**Comment by pedropla** [comment] 2021-08-12 01:32
Do you need an entire project or would a prefab of a particular light with your script and the issue work? A prefab is easier to export, for a project I'd need to create a new bare bones project, import some lights and bakery and test, etc.

**Comment by guycalledfrank** [comment] 2021-08-18 22:24
If this prefab shows the issue in a fresh project, then prefab is enough.

**Comment by pedropla** [comment] 2022-01-05 04:56
Since it's working in recent Bakery builds I think it can be closed.

**Closed as completed** 2022-01-05 10:01 UTC
